### ISSUE TITLE
seems to be not working in developer mode

### ISSUE THREAD

**Issue by onlinebizsoft** [zepgram/module-zero-downtime-deployment#3]
When the developer mode is enabled and the cache is disabled, look like we still see the DB validator exception?

**Comment by zepgram** [comment]
The module is effective only on production mode.
This allow developers to know when they need to run setup:upgrade after pulling a branch for example.

**Comment by onlinebizsoft** [comment]
@zepgram it is possible to allow it working in the developer mode because sometime developers need to checkout some code version for checking some issues.

It is really helpful. Do you agree?

**Comment by zepgram** [comment]
I could make a configuration for it but I'm not sure to understand your needs. 
- When you are on developer mode you do not require zero down time (there is no customer, only developers).
- In production or preproduction environments your Magento is supposed to be in production mode, not in developer mode.

So why do you need zero downtime on a developer environment ?

**Comment by onlinebizsoft** [comment]
@zepgram It is not downtime during the deployment but I think Magento validate the data version of what saved in the db and what in the codebase so it gives the exception when we run the old code version with a newer db. Is that correct?

**Comment by zepgram** [comment]
Yes you're right. When you rollback your code you can face this issue. Now I understand 😉

I'll made a configuration, is that ok for you ?

**Comment by onlinebizsoft** [comment]
Perfect! But it isnt possible to work with both mode automatically?

**Comment by zepgram** [comment]
Yes, but as I said before you may need this error as a developer when your code is not up to date during development.
So for me, you should force this configuration only for specific purpose.

**Comment by zepgram** [comment]
Well it's done on release v0.0.4

Tell me if it's fine for you. Don't forget to put a star 👍🏻 

Thank you in advance.
